Unit2_Django Models/Lesson8_Custom_User_Form/myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index),
    path('about/', views.about),
    path('posts/', include('posts.urls')),
    path('users/', include('users.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/posts/urls.py
from django.urls import path
from . import views
app_name = 'posts'

urlpatterns = [
    path('', views.posts_list, name = "list"),
    path('<slug:slug>', views.post_page, name = "page"),
]

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/users/urls.py
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('register/', views.register, name='register'),
    path('login/', views.login_view, name='login'),
]

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/posts/models.py
from django.db import models

# Create your models here.
class Post(models.Model):
    title = models.CharField(max_length=75)
    body = models.TextField()
    slug = models.SlugField()
    date = models.DateTimeField(auto_now_add=True)
    banner = models.ImageField(default='fallback.png', blank=True)
    
    def __str__(self):
        return self.title

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/users/models.py
from django.db import models

# Create your models here.

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class CustomUserCreationForm(UserCreationForm):
    email = forms.EmailField(required=True)
    first_name = forms.CharField(max_length=30, required=True)
    last_name = forms.CharField(max_length=30)
    
    class Meta:
        model = User
        fields = ("username", "email", "first_name", "last_name", "password1", "password2")
    
    def save(self, commit=True):
        user = super().save(commit=False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']
        if commit:
            user.save()
        return user

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/myproject/views.py
from django.shortcuts import render
def index(request):
    context = {
        'active_link': 'home'
    }
    return render(request, 'index.html', context)

def about(request):
    context = {
        'active_link':'about'
    }
    return render(request, 'about.html',context)

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/posts/views.py
from django.shortcuts import render
from .models import Post
# from django.http import HttpResponse

# Create your views here.
def posts_list(request):
    # posts = Post.objects.all()
    posts = Post.objects.all().order_by('date')
    context = {
        'active_link': 'posts',
        'posts':posts
    }
    return render(request,'posts/posts_list.html', context)
def post_page(request, slug):
    # return HttpResponse(slug)
    post = Post.objects.get(slug=slug)
    return render(request, 'posts/post_page.html',{'post':post} )

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from .forms import CustomUserCreationForm

def register(request):
    #Check if the form is submitted
    if request.method == "POST":
        form = CustomUserCreationForm(request.POST) #submitted with data
        #validate the form
        if form.is_valid():
            form.save()
            return redirect("posts:list")
    else: #Get method
        form = CustomUserCreationForm()
    context = {
        'active_link': 'register',
        'form':form
    }
    return render(request, 'users/register.html', context)

def login_view(request):
    if request.method == "POST":
        form = AuthenticationForm(data = request.POST)
        if form.is_valid():
            # LOGIN HERE
            return redirect("posts:list")
    else:
        form = AuthenticationForm()
    # Add Boostrsap classes to the form field
    for field in form.fields.values():
        field.widget.attrs["class"] = "form-control"
    context = {"active_link":"login", 'form':form}
    return render(request, "users/login.html", context)

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/templates/about.html
{% extends "base.html"%}
{% load static %}
{% block title %}ABOUT{% endblock title %}

{% block header_image %}
<img class="masthead-avatar mb-5" src="{% static 'assets/blog/about.png' %}" alt="..." />
{% endblock header_image %}

{% block header_title %}ABOUT ME{% endblock header_title %}

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/templates/base.html
<!DOCTYPE html>
{%load static%}
<html lang="en">
``    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>{% block title %}{% endblock title %}</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{% static 'assets/favicon.ico' %}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
        {% block head %}{% endblock head %}
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
                <a class="navbar-brand" href="#page-top">DJANGO BLOG</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'home' %}active{% endif %}" href="/">Home</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'about' %}active{% endif %}" href="/about">About</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'posts' %}active{% endif %}" href="{% url 'posts:list' %}">Posts</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'register' %}active{% endif %}" href="{% url 'users:register' %}">Register</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded {% if active_link == 'login' %}active{% endif %}" href="{% url 'users:login' %}">Login</a></li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            <div class="container d-flex align-items-center flex-column">
                <!-- Masthead Avatar Image-->
                {%block header_image%}
                {%endblock header_image%}
                <!-- Masthead Heading-->
                <h1 class="masthead-heading text-uppercase mb-0">{% block header_title %}{% endblock header_title %}</h1>
                <!-- Icon Divider-->
                <div class="divider-custom divider-light">
                    <div class="divider-custom-line"></div>
                    <div class="divider-custom-icon"><i class="fas fa-star"></i></div>
                    <div class="divider-custom-line"></div>
                </div>
                <!-- Masthead Subheading-->
                {% comment %} <p class="masthead-subheading font-weight-light mb-0">Graphic Artist - Web Designer - Illustrator</p> {% endcomment %}
                {% block content %}{% endblock content %}
            </div>
        </header>

        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Location-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Location</h4>
                        <p class="lead mb-0">
                            2215 John Daniel Drive
                            <br />
                            Clark, MO 65243
                        </p>
                    </div>
                    <!-- Footer Social Icons-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Around the Web</h4>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-facebook-f"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-twitter"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-linkedin-in"></i></a>
                        <a class="btn btn-outline-light btn-social mx-1" href="#!"><i class="fab fa-fw fa-dribbble"></i></a>
                    </div>
                    <!-- Footer About Text-->
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">About Freelancer</h4>
                        <p class="lead mb-0">
                            Freelance is a free to use, MIT licensed Bootstrap theme created by
                            <a href="http://startbootstrap.com">Start Bootstrap</a>
                            .
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        <div class="copyright py-4 text-center text-white">
            <div class="container"><small>Copyright &copy; Your Website 2023</small></div>
        </div>

        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{% static 'js/scripts.js' %}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/templates/index.html
{% extends "base.html"%}
{% load static %}
{% block title %}HOME PAGE{% endblock title %}

{% block header_image %}
<img class="masthead-avatar mb-5" src="{% static 'assets/blog/homepage.png' %}" alt="..." />
{% endblock header_image %}


{% block header_title %}HOME PAGE{% endblock header_title %}

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/users/templates/users/login.html
{% extends "base.html" %}  <!-- Extend the base template -->
{% load static %}          <!-- Load static files -->

{% block title %}Login User{% endblock title %}  <!-- Set the title -->

{% block header_image %}
    <img src="{% static 'assets/blog/login.png' %}" alt="Register" width="200px" class="register-image">  <!-- Add the image in the header_image block -->
{% endblock header_image %}

{% block content %}   <!-- Define content block -->
    <h1>Login User</h1>  <!-- Heading text -->
    <form action="/users/login/" method="POST" class="p-4 border rounded bg-light text-dark">
        {% csrf_token %}{% comment %}  # security token Cross-site Request Forgery Attacks {% endcomment %}
        {% comment %} {{form}} {% endcomment %}
        {% comment %} Display Form Errors {% endcomment %}
        {%if form.errors%}
        <div class="alert alert-danger">
            <ul>
                {%for field in form%}
                    {%if field.errors%}
                        <li>{{field.label}}:{{field.errors}}</li>
                    {%endif%}
                {%endfor%}
            </ul>
        </div>
        {%endif%}

        <div class="container text-center">
            <div class="row mb-3">
                <div class="col sm-6">
                    <label for="{{form.username.id_for_label}}" class="form-label">Username</label>
                </div>
                <div class="col sm-6">
                    {{form.username}}
                </div>
            </div>
            <div class="row mb-3">
                <div class="col sm-6">
                    <label for="{{form.password.id_for_label}}" class="form-label">Password</label>
                </div>
                <div class="col sm-6">
                    {{form.password}}
                </div>
            </div>

        </div>
        

       
        <button>Submit</button>
    </form>
{% endblock content %}

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/users/templates/users/register.html
{% extends "base.html" %}  <!-- Extend the base template -->
{% load static %}          <!-- Load static files -->

{% block title %}Register a New User{% endblock title %}  <!-- Set the title -->

{% block header_image %}
    <img src="{% static 'assets/blog/register.png' %}" alt="Register" width="200px" class="register-image">  <!-- Add the image in the header_image block -->
{% endblock header_image %}

{% block content %}   <!-- Define content block -->
    <h1>Register a New User</h1>  <!-- Heading text -->
    <form action="/users/register/" method="POST" class="p-4 border rounded bg-light text-dark">
        {% comment %} {% csrf_token %} # security token Cross-site Request Forgery Attacks {% endcomment %}
        {% csrf_token %}
        {% comment %} {{form}} {% endcomment %}
        {% comment %} Display Form Errors {% endcomment %}
        {%if form.error%}
        <div class="alert alert-danger">
            <ul>
                {%for field in form%}
                    {%if field.error%}
                        <li>{{field.label}}:{{field.errors}}</li>
                    {%endif%}
                {%endfor%}
            </ul>
        </div>
        {%endif%}
        <div class="mb-3">
            <label for="{{form.username.id_for_label}}">Username:</label>
            {{form.username}}
        </div>
        <div class="mb-3">
            <label for="{{form.email.id_for_label}}">Email:</label>
            {{form.email}}
        </div>
        <div class="mb-3">
            <label for="{{form.first_name.id_for_label}}">First Name:</label>
            {{form.first_name}}
        </div>
        <div class="mb-3">
            <label for="{{form.last_name.id_for_label}}">Last Name:</label>
            {{form.last_name}}
        </div>
        <div class="mb-3">
            <label for="{{form.password1.id_for_label}}">Password:</label>
            {{form.password1}}
        </div>
        <div class="mb-3">
            <label for="{{form.password2.id_for_label}}">Password Confirmation:</label>
            {{form.password2}}
        </div>
        <button>Submit</button>
    </form>
{% endblock content %}

Unit2_Django Models/Lesson8_Custom_User_Form/myproject/users/templates/users/register_backup.html
{% extends "base.html" %}  <!-- Extend the base template -->
{% load static %}          <!-- Load static files -->

{% block title %}Register a New User{% endblock title %}  <!-- Set the title -->

{% block header_image %}
    <img src="{% static 'assets/blog/register.png' %}" alt="Register" width="200px" class="register-image">  <!-- Add the image in the header_image block -->
{% endblock header_image %}

{% block content %}   <!-- Define content block -->
    <h1>Register a New User</h1>  <!-- Heading text -->
    <form action="/users/register/" method="POST" class="p-4 border rounded bg-light text-dark">
        {% csrf_token %}{% comment %}  # security token Cross-site Request Forgery Attacks {% endcomment %}
        {% comment %} {{form}} {% endcomment %}
        {% comment %} Display Form Errors {% endcomment %}
        {%if form.errors%}
        <div class="alert alert-danger">
            <ul>
                {%for field in form%}
                    {%if field.errors%}
                        <li>{{field.label}}:{{field.errors}}</li>
                    {%endif%}
                {%endfor%}
            </ul>
        </div>
        {%endif%}

        <div class="mb-3">
         <label for="{{form.username.id_for_label}}">Username</label>
         {{form.username}}   
        </div>
        
        <div class="mb-3">
         <label for="{{form.email.id_for_label}}">Email</label>
         {{form.email}}   
        </div>

        <div class="mb-3">
         <label for="{{form.first_name.id_for_label}}">First Name</label>
         {{form.first_name}}   
        </div>

        <div class="mb-3">
         <label for="{{form.last_name.id_for_label}}">Last Name</label>
         {{form.last_name}}   
        </div>

        <div class="mb-3">
            <label for="{{form.password1.id_for_label}}">Password</label>
            {{form.password1}}
        </div>
        <div class="mb-3">
            <label for="{{form.password2.id_for_label}}">Password Confirmation</label>
            {{form.password2}}
        </div>
        

       
        <button>Submit</button>
    </form>
{% endblock content %}